# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-performance

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml

inherit_from:
  - .rubocop/rails.yml

# Global options, like Ruby version
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2